apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: budget-app-run
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: budget-app-pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          name: source-pvc
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 500Mi
