apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      containers:
      - name: budget-app
        image: your_dockerhub_username/budget-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: password
        - name: DATABASE_NAME
          value: budget_db
---
apiVersion: v1
kind: Service
metadata:
  name: budget-service
spec:
  selector:
    app: budget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
